# Generated by Django 4.0.5 on 2022-07-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybecoffeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence',
            name='depart_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
